env:
  - GO11MODULE=on
  - GO111MODULE=on
  - GOPROXY=https://goproxy.io
  - CGO_ENABLED=0

before:
  hooks:
    - go mod tidy

release:
  draft: true

builds:
  - id: build-linux
    main: .
    binary: actiondev
    ldflags: -s -w -X main.Version={{.Version}} -X main.Revision={{.ShortCommit}} -X main.Time={{.Date}} -X main.BuildUser=goreleaser
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - replacements:
      darwin: macOS
      amd64: x86_64
      linux: Linux
      windows: Windows
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# goreleaser release --snapshot --rm-dist
