apiVersion: apps/v1
kind: Deployment
metadata:
  name: actions-runner
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: actions-runner
  template:
    metadata:
      labels:
        app: actions-runner
    spec:
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
      - name: workdir
        hostPath:
          path: /tmp/github-runner-aiworklab
      containers:
      - name: runner
        image: registry.cn-hangzhou.aliyuncs.com/aigitlab/github-runner:latest
        env:
        - name: ACCESS_TOKEN
          value: xxxxxxx
        - name: LABELS
          value: test,my-label,other-label
        - name: REPO_URL
          value: https://github.com/aiworklab/actiondev
        - name: RUNNER_NAME_PREFIX
          value: actiondev
        - name: RUNNER_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: RUNNER_WORKDIR
          value: /tmp/github-runner-aiworklab
        volumeMounts:
        - name: dockersock
          mountPath: /var/run/docker.sock
        - name: workdir
          mountPath: /tmp/github-runner-aiworklab