name: Build Docker Hub Image

on:
  push:
    branches: [ "githubaction" ]
    tags:
      - v2.*
      - v1.*
      - v0.*
  # pull_request:
  #   branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE: aiworklab/actiondev

jobs:
  build:
    runs-on: [self-hosted, linux]
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        platforms: linux/amd64,linux/arm64
        version: latest
        endpoint: builders
        driver: docker

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: aichy66/actiondev
        tags: |
              type=raw,value=latest
              # branch event
              type=ref,enable=true,priority=600,prefix=,suffix=,event=branch
              # tag event
              #type=ref,enable=true,priority=600,prefix=,suffix=,event=tag
              type=semver,pattern={{version}}
    - name: Build amd64
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    # - name: Build arm64
    #   uses: docker/build-push-action@v4
    #   with:
    #     context: .
    #     file: ./Dockerfile
    #     platforms: linux/arm64
    #     push: true
    #     tags: ${{ steps.meta.outputs.tags }}
    #     labels: ${{ steps.meta.outputs.labels }}

    - name: Push image to GHCR
      run: |
        docker buildx imagetools create \
          --tag ghcr.io/${{ env.REGISTRY }}/${{ env.IMAGE }}:latest
          ${{ env.REGISTRY }}/${{ env.IMAGE }}:latest
